server:
  port: 8082

spring:
  application:
    name: unitech
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unitech
    username: postgres
    password: admin

  jpa:
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

currency:
  api:
    url: https://open.er-api.com/v6/latest